=== epam/ACUITY/clns-acuity-admin/acuity-core/src/main/resources/EntitiesDescription.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright 2021 The University of Manchester
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~     http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://visualisations.acuity.com/EntitiesDescription"
        xmlns:tns="http://visualisations.acuity.com/EntitiesDescription" elementFormDefault="qualified">

    <complexType name="EntitiesRootRule">
        <sequence>
            <element name="entity" type="tns:EntityDescriptionRule" maxOccurs="unbounded" minOccurs="0"></element>
        </sequence>
    </complexType>

    <complexType name="EntityDescriptionRule">
        <complexContent>
            <extension base="tns:EntityBaseRule">
                <sequence>
                    <element name="mandatory" type="boolean" default="false"/>
                    <element name="uniqueFields" type="tns:EntityFieldSetRule" minOccurs="1" maxOccurs="1"/>
                    <element name="secondaryFields" type="tns:EntityFieldSetRule" minOccurs="1" maxOccurs="1"/>
                    <element name="referredBy" type="tns:EntityReferedByRule" minOccurs="0" maxOccurs="unbounded"/>
                    <element name="referBy" type="tns:EntityFieldSetRule" minOccurs="0" maxOccurs="unbounded"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="EntityReferedByRule">
        <complexContent>
            <extension base="tns:EntityFieldSetRule">
                <attribute name="equalToUniqueSet" type="boolean" default="false"/>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="EntityBaseRule">
        <attribute name="name" type="string"></attribute>
    </complexType>

    <complexType name="EntityFieldSetRule">
        <complexContent>
            <extension base="tns:EntityBaseRule">
                <sequence>
                    <element maxOccurs="unbounded" minOccurs="0" name="field" type="tns:EntityBaseRule"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <element name="root" type="tns:EntitiesRootRule"></element>

</schema>

=== epam/ACUITY/clns-acuity-admin/acuity-core/src/main/resources/EntitiesDescription.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
  ~ Copyright 2021 The University of Manchester
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~     http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<root xmlns="http://visualisations.acuity.com/EntitiesDescription" schemaLocation="EntitiesDescription.xsd">

    <entity name="PatientGroup" table="RESULT_PATIENT_GROUP">
        <uniqueFields>
            <field name="groupingName"/>
            <field name="subject"/>
            <field name="studyName"/>
            <field name="projectName"/>
        </uniqueFields>
        <secondaryFields>
            <field name="part"/>
            <field name="groupName"/>
        </secondaryFields>
        <referredBy name="patGroupUnique" equalToUniqueSet="true"/>
        <referBy name="studyUnique">
            <field name="studyName"/>
            <field name="projectName"/>
        </referBy>
    </entity>

    <entity name="Patient" table="RESULT_PATIENT">
        <uniqueFields>
            <field name="subject"/>
            <field name="studyName"/>
            <field name="projectName"/>
        </uniqueFields>
        <secondaryFields>
            <field name="race"/>
            <field name="sex"/>
            <field name="centre"/>
            <field name="birthDate"/>
            <field name="visitDate"/>
            <field name="part"/>
        </secondaryFields>
        <referredBy name="patUnique" equalToUniqueSet="true"/>
        <referBy name="studyUnique">
            <field name="studyName"/>
            <field name="projectName"/>
        </referBy>
        <referBy name="patGroupUnique">
            <field name="subject"/>
            <field name="studyName"/>
            <field name="projectName"/>
        </referBy>
        <mandatory>true</mandatory>
    </entity>

    <entity name="Death" table="RESULT_DEATH">
        <uniqueFields>
            <field name="subject"/>
            <field name="studyName"/>
            <field name="projectName"/>
            <field name="designationOfCause"/>
        </uniqueFields>
        <secondaryFields>
            <field name="part"/>
            <field name="date"/>
            <field name="cause"/>
            <field name="autopsyPerformed"/>
            <field name="relatedToInvestigationDisease"/>
            <field name="narrativeCause"/>
            <field name="preferredTerm"/>
            <field name="llt"/>
            <field name="hlt"/>
            <field name="soc"/>
        </secondaryFields>
        <referBy name="patUnique">
            <field name="subject"/>
            <field name="studyName"/>
            <field name="projectName"/>
        </referBy>
    </entity>

    <entity name="PrimaryTumourLocation" table="RESULT_PRIMARY_TUMOUR_LOCATION">
        <uniqueFields>
            <field name="subject"/>
            <field name="studyName"/>
            <field name="projectName"/>
        </uniqueFields>
        <secondaryFields>
            <field name="part"/>
            <field name="primaryTumLocation"/>
            <field name="originalDiagnosisDate"/>
            <field name="primaryTumLocationComment"/>
        </secondaryFields>
        <referBy name="patUnique">
            <field name="subject"/>
            <field name="studyName"/>
            <field name="projectName"/>
        </referBy>
    </entity>

    <entity name="Visit" table="RESULT_VISIT">
        <uniqueFields>
            <field name="visitDate"/>
            <field name="subject"/>
            <field name="studyName"/>
            <field name="projectName"/>
        </uniqueFields>
        <secondaryFields>
            <field name="visitNumber"/>
            <field name="part"/>
        </secondaryFields>
        <referBy name="patUnique">
            <field name="subject"/>
            <field name="studyName"/>
            <field name="projectName"/>
        </referBy>
        <mandatory>true</mandatory>
    </entity>

    <entity name="Country" table="RESULT_COUNTRY">
        <uniqueFields>
            <field name="subject"/>
            <field name="studyName"/>
            <field name="projectName"/>
        </uniqueFields>
        <secondaryFields>
            <field name="countryName"/>
            <field name="part"/>
        </secondaryFields>
        <referBy name="patUnique">
            <field name="subject"/>
            <field name="studyName"/>
            <field name="projectName"/>
        </referBy>
    </entity>

    <entity name="Randomisation" table="RESULT_RANDOMISATION">
        <uniqueFields>
            <field name="subject"/>
            <field name="studyName"/>
            <field name="projectName"/>
        </uniqueFields>
        <secondaryFields>
            <field name="randDate"/>
            <field name="part"/>
        </secondaryFields>
        <referBy name="patUnique">
            <field name="subject"/>
            <field name="studyName"/>
            <field name="projectName"/>
        </referBy>
    </entity>

    <entity name="EventType" table="RESULT_EVENT_TYPE">
        <uniqueFields>
            <field name="PT"/>
            <field name="HLT"/>
            <field name="SOC"/>
            <field name="studyName"/>
            <field name="projectName"/>
        </uniqueFields>
        <secondaryFields>
            <field name="LLT"/>
            <field name="medDRAVersion"/>
        </secondaryFields>
        <referredBy name="evtUnique" equalToUniqueSet="true"/>
        <referBy name="studyUnique">
            <field name="studyName"/>
            <field name="projectName"/>
        </referBy>
        <referBy name="aegUnique">
            <field name="PT"/>
            <field name="studyName"/>
            <field name="projectName"/>
        </referBy>
    </entity>

    <entity name="AE" table="RESULT_AE">
        <uniqueFields>
            <field name="PT"/>
            <field name="HLT"/>
            <field name="SOC"/>
            <field name="startDate"/>
            <field name="subject"/>
            <field name="studyName"/>
            <field name="projectName"/>
        </uniqueFields>
        <secondaryFields>
            <field name="serious"/>
            <field name="number"/>
            <field name="aeText"/>
            <field name="comment"/>
            <field name="outcome"/>
            <field name="doseLimitingToxicity"/>
            <field name="timePoint"/>
            <field name="immuneMediated"/>
            <field name="infusionReaction"/>
            <field name="requiredTreatment"/>
            <field name="causedSubjectWithdrawal"/>
        </secondaryFields>
        <referBy name="evtUnique">
            <field name="PT"/>
            <field name="HLT"/>
            <field name="SOC"/>
            <field name="studyName"/>
            <field name="projectName"/>
        </referBy>
        <referBy name="patUnique">
            <field name="subject"/>
            <field name="studyName"/>
            <field name="projectName"/>
        </referBy>
        <referredBy name="aeUnique" equalToUniqueSet="true"/>
    </entity>

    <entity name="AeSeverity" table="RESULT_AE_SEVERITY">
        <uniqueFields>
            <field name="aeUniqueFields"/>
            <field name="startDate"/>
        </uniqueFields>
        <secondaryFields>
            <field name="severity"/>
            <field name="endDate"/>
        </secondaryFields>
        <referBy name="aeUnique">
            <field name="aePT"/>
            <field name="aeHLT"/>
            <field name="aeSOC"/>
            <field name="aeStartDate"/>
            <field name="aeSubject"/>
            <field name="studyName"/>
            <field name="projectName"/>
        </referBy>
        <referredBy name="aeSeverityUnique" equalToUniqueSet="true"/>
    </entity>

    <entity name="AeCausality" table="RESULT_AE_CAUSALITY">
        <uniqueFields>
            <field name="aeUniqueFields"/>
            <field name="drugUniqueFields"/>
        </uniqueFields>
        <secondaryFields>
            <field name="causality"/>
        </secondaryFields>
        <referBy name="aeUnique">
            <field name="aePT"/>
            <field name="aeHLT"/>
            <field name="aeSOC"/>
            <field name="aeStartDate"/>
            <field name="aeSubject"/>
            <field name="studyName"/>
            <field name="projectName"/>
        </referBy>
        <referBy name="drugUnique">
            <field name="drugName"/>
            <field name="studyName"/>
            <field name="projectName"/>
        </referBy>
    </entity>

    <entity name="AeActionTaken" table="RESULT_AE_ACTION_TAKEN">
        <uniqueFields>
            <field name="aeSeverityUniqueFields"/>
            <field name="drugUniqueFields"/>
        </uniqueFields>
        <secondaryFields>
            <field name="actionTaken"/>
        </secondaryFields>
        <referBy name="aeSeverityUnique">
            <field name="aeUniqueFields"/>
            <field name="aeSeverityStartDate"/>
        </referBy>
        <referBy name="drugUnique">
            <field name="drugName"/>
            <field name="studyName"/>
            <field name="projectName"/>
        </referBy>
    </entity>

    <entity name="Drug" table="RESULT_DRUG">
        <uniqueFields>
            <field name="drugName"/>
            <field name="studyName"/>
            <field name="projectName"/>
        </uniqueFields>
        <referBy name="studyUnique">
            <field name="studyName"/>
            <field name="projectName"/>
