=== epam/ACUITY/clns-acuity-admin/acuity-core/src/main/resources/TablesDescription.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright 2021 The University of Manchester
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~     http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://visualisations.acuity.com/TablesDescription"
        xmlns:tns="http://visualisations.acuity.com/TablesDescription" elementFormDefault="qualified">

    <complexType name="TablesRootRule">
        <sequence>
            <element name="table" type="tns:TableRule" maxOccurs="unbounded" minOccurs="0"></element>
        </sequence>
    </complexType>

    <complexType name="TableRule">
        <complexContent>
            <extension base="tns:TableBaseRule">
                <sequence>
                    <element name="foreignKey" type="tns:ForeignKeyRule" minOccurs="0" maxOccurs="unbounded"/>
                    <element name="uniqueFields" type="tns:TableFieldSetRule" minOccurs="1" maxOccurs="1"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="ForeignKeyRule">
        <attribute name="targetTable" type="string"/>
        <attribute name="source" type="string"/>
        <attribute name="target" type="string"/>
        <attribute name="fkField" type="string"/>
        <attribute name="nullable" type="boolean"/>
    </complexType>

    <complexType name="TableFieldSetRule">
        <sequence>
            <element maxOccurs="unbounded" minOccurs="0" name="field" nillable="true" type="tns:TableBaseRule"/>
        </sequence>
    </complexType>

    <complexType name="TableBaseRule">
        <attribute name="name" type="string"></attribute>
    </complexType>

    <element name="root" type="tns:TablesRootRule"></element>

</schema>

=== epam/ACUITY/clns-acuity-admin/acuity-core/src/main/resources/TablesDescription.xml
<?xml version="1.0" encoding="UTF-8"?>

<root xmlns="http://visualisations.acuity.com/TablesDescription" schemaLocation="TablesDescription.xsd">

    <table name="RESULT_PATIENT_GROUP">
        <foreignKey targetTable="RESULT_STUDY" source="studyUnique" target="studyUnique" fkField="studyGuid"/>
        <uniqueFields>
            <field name="studyGuid"/>
            <field name="subject"/>
            <field name="part"/>
        </uniqueFields>
    </table>
    <table name="RESULT_PATIENT">
        <foreignKey targetTable="RESULT_STUDY" source="studyUnique" target="studyUnique" fkField="studyGuid"/>
        <foreignKey targetTable="RESULT_PATIENT_GROUP" source="patUnique" target="patUnique" nullable="true"
                    fkField="patientGroupGuid"/>
        <uniqueFields>
            <field name="studyGuid"/>
            <field name="subject"/>
        </uniqueFields>
    </table>

    <table name="RESULT_DEATH">
        <foreignKey targetTable="RESULT_PATIENT" source="patUnique" target="patUnique" fkField="patientGuid"/>
        <uniqueFields>
            <field name="patientGuid"/>
        </uniqueFields>
    </table>

    <table name="RESULT_PRIMARY_TUMOUR_LOCATION">
        <foreignKey targetTable="RESULT_PATIENT" source="patUnique" target="patUnique" fkField="patientGuid"/>
        <uniqueFields>
            <field name="patientGuid"/>
        </uniqueFields>
    </table>

    <table name="RESULT_VISIT">
        <foreignKey targetTable="RESULT_PATIENT" source="patUnique" target="patUnique" fkField="patientGuid"/>
        <uniqueFields>
            <field name="patientGuid"/>
            <field name="visitDate"/>
        </uniqueFields>
    </table>

    <table name="RESULT_COUNTRY">
        <foreignKey targetTable="RESULT_PATIENT" source="patUnique" target="patUnique" fkField="patientGuid"/>
        <uniqueFields>
            <field name="patientGuid"/>
        </uniqueFields>
    </table>

    <table name="RESULT_RANDOMISATION">
        <foreignKey targetTable="RESULT_PATIENT" source="patUnique" target="patUnique" fkField="patientGuid"/>
        <uniqueFields>
            <field name="patientGuid"/>
        </uniqueFields>
    </table>

    <table name="RESULT_EVENT_TYPE">
        <foreignKey targetTable="RESULT_STUDY" source="studyUnique" target="studyUnique" fkField="studyGuid"/>
        <uniqueFields>
            <field name="studyGuid"/>
            <field name="PT"/>
        </uniqueFields>
    </table>


    <table name="RESULT_AE">
        <foreignKey targetTable="RESULT_EVENT_TYPE" source="evtUnique" target="evtUnique" fkField="eventTypeGuid"/>
        <foreignKey targetTable="RESULT_PATIENT" source="patUnique" target="patUnique" fkField="patientGuid"/>
        <uniqueFields>
            <field name="patientGuid"/>
            <field name="eventTypeGuid"/>
            <field name="startDate"/>
        </uniqueFields>
    </table>

    <table name="RESULT_AE_SEVERITY">
        <foreignKey targetTable="RESULT_AE" source="aeUnique" target="aeUnique" fkField="aeGuid"/>
        <uniqueFields>
            <field name="aeGuid"/>
            <field name="startDate"/>
        </uniqueFields>
    </table>

    <table name="RESULT_AE_CAUSALITY">
        <foreignKey targetTable="RESULT_AE" source="aeUnique" target="aeUnique" fkField="aeGuid"/>
        <foreignKey targetTable="RESULT_DRUG" source="drugUnique" target="drugUnique" fkField="drugGuid"/>
        <uniqueFields>
            <field name="aeGuid"/>
            <field name="drugGuid"/>
        </uniqueFields>
    </table>

    <table name="RESULT_AE_ACTION_TAKEN">
        <foreignKey targetTable="RESULT_AE_SEVERITY" source="aeSeverityUnique" target="aeSeverityUnique"
                    fkField="aeSeverityGuid"/>
        <foreignKey targetTable="RESULT_DRUG" source="drugUnique" target="drugUnique" fkField="drugGuid"/>
        <uniqueFields>
            <field name="aeSeverityGuid"/>
            <field name="drugGuid"/>
        </uniqueFields>
    </table>

    <table name="RESULT_DRUG">
        <foreignKey targetTable="RESULT_STUDY" source="studyUnique" target="studyUnique" fkField="studyGuid"/>
        <uniqueFields>
            <field name="studyGuid"/>
            <field name="drugName"/>
        </uniqueFields>
    </table>

    <table name="RESULT_SERIOUS_ADVERSE_EVENT">
        <foreignKey targetTable="RESULT_PATIENT" source="patUnique" target="patUnique" fkField="patientGuid"/>
        <uniqueFields>
            <field name="patientGuid"/>
            <field name="aeText"/>
            <field name="aeBecomeSeriousDate"/>
        </uniqueFields>
    </table>

    <table name="RESULT_TEST">
        <foreignKey targetTable="RESULT_PATIENT" source="patUnique" target="patUnique" fkField="patientGuid"/>
        <uniqueFields>
            <field name="patientGuid"/>
            <field name="date"/>
        </uniqueFields>
    </table>

    <table name="RESULT_LAB_GROUP">
        <foreignKey targetTable="RESULT_STUDY" source="studyUnique" target="studyUnique" fkField="studyGuid"/>
        <uniqueFields>
            <field name="studyGuid"/>
            <field name="labCode"/>
        </uniqueFields>
    </table>

    <table name="RESULT_LABORATORY">
        <foreignKey targetTable="RESULT_LAB_GROUP" source="lgrUnique" target="lgrUnique" nullable="true"
                    fkField="laboratoryGroupGuid"/>
        <foreignKey targetTable="RESULT_TEST" source="testUnique" target="testUnique" fkField="testGuid"/>
        <foreignKey targetTable="RESULT_SOURCE" source="srcUnique" target="srcUnique" fkField="sourceGiud" nullable="true"/>
        <uniqueFields>
            <field name="testGuid"/>
            <field name="sourceGiud"/>
            <field name="labCode"/>
        </uniqueFields>
    </table>

    <table name="RESULT_SOURCE">
        <uniqueFields>
            <field name="name"/>
            <field name="version"/>
            <field name="type"/>
        </uniqueFields>
    </table>

    <table name="RESULT_PATIENT_REPORTED_DATA">
        <foreignKey targetTable="RESULT_SOURCE" source="srcUnique" target="srcUnique" fkField="sourceGiud" nullable="true"/>
        <foreignKey targetTable="RESULT_PATIENT" source="patUnique" target="patUnique" fkField="patientGuid"/>
        <uniqueFields>
            <field name="subject"/>
            <field name="measurementName"/>
            <field name="measurementDate"/>
            <field name="reportDate"/>
            <field name="part"/>
            <field name="value"/>
            <field name="unit"/>
            <field name="comment"/>
            <field name="sourceType"/>
            <field name="sourceGiud"/>
        </uniqueFields>
    </table>

    <!--<table name="RESULT_ECG">-->
    <!--<foreignKey targetTable="RESULT_TEST" source="testUnique" target="testUnique" fkField="testGuid"/>-->
    <!--<uniqueFields>-->
    <!--<field name="testGuid"/>-->
    <!--<field name="testName"/>-->
    <!--<field name="resultUnit"/>-->
    <!--</uniqueFields>-->
    <!--</table>-->

    <table name="RESULT_EG">
        <foreignKey targetTable="RESULT_TEST" source="testUnique" target="testUnique" fkField="testGuid"/>
        <uniqueFields>
            <field name="testGuid"/>
            <field name="testName"/>
            <field name="resultUnit"/>
        </uniqueFields>
    </table>

    <table name="RESULT_DECG">
        <foreignKey targetTable="RESULT_TEST" source="testUnique" target="testUnique" fkField="testGuid"/>
        <uniqueFields>
            <field name="testGuid"/>
            <field name="measurementLabel"/>
        </uniqueFields>
    </table>

    <table name="RESULT_LVEF">
        <foreignKey targetTable="RESULT_TEST" source="testUnique" target="testUnique" fkField="testGuid"/>
        <uniqueFields>
            <field name="testGuid"/>
        </uniqueFields>
    </table>

    <table name="RESULT_VITALS">
        <foreignKey targetTable="RESULT_TEST" source="testUnique" target="testUnique" fkField="testGuid"/>
        <uniqueFields>
            <field name="testGuid"/>
            <field name="testName"/>
            <field name="resultUnit"/>
            <field name="anatomicalLocation"/>
            <field name="physicalPosition"/>
            <field name="anatomicalSideOfInterest"/>
        </uniqueFields>
    </table>

    <table name="RESULT_MEDICINE">
        <foreignKey targetTable="RESULT_STUDY" source="studyUnique" target="studyUnique" fkField="studyGuid"/>
        <uniqueFields>
            <field name="studyGuid"/>
            <field name="drugName"/>
            <field name="drugParent"/>
        </uniqueFields>
    </table>

    <table name="RESULT_CONMED_SCHEDULE">
        <foreignKey targetTable="RESULT_MEDICINE" source="medUnique" target="medUnique" fkField="medicineGuid"/>
        <foreignKey targetTable="RESULT_PATIENT" source="patUnique" target="patUnique" fkField="patientGuid"/>
        <uniqueFields>
            <field name="medicineGuid"/>
            <field name="patientGuid"/>
            <field name="startDate"/>
            <field name="aeNumber"/>
        </uniqueFields>
    </table>

    <table name="RESULT_TRG_MED_DOS_SCHEDULE">
        <foreignKey targetTable="RESULT_PATIENT" source="patUnique" target="patUnique" fkField="patientGuid"/>
        <uniqueFields>
            <field name="patientGuid"/>
            <field name="drug"/>
            <field name="startDate"/>
        </uniqueFields>
    </table>

    <table name="RESULT_AE_NUM_ACT_TAKEN">
        <foreignKey targetTable="RESULT_TRG_MED_DOS_SCHEDULE" source="doseUnique" target="doseUnique"
                    fkField="doseGuid"/>
        <foreignKey targetTable="RESULT_PATIENT" source="patUnique" target="patUnique" fkField="patientGuid"/>
        <uniqueFields>
            <field name="doseGuid"/>
            <field name="patientGuid"/>
            <field name="numActionTaken"/>
        </uniqueFields>
    </table>

    <table name="RESULT_AE_NUM_DEL">
